language: node_js
node_js:
- '6.10'
branches:
  only:
  - blog-source
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "Hzwcode"
- git config --global user.email 1359434736@qq.com
- sed -i'' "s~git@github.com:Hzwcode/Hzwcode.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/Hzwcode/Hzwcode.github.io.git~"
  _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
env:
  global:
    secure: SG+tFjZrqAxFPew/9xT4KvCQn+YaTjFzZkoPxhJl5+tT5DYDv/4UjM+iYDGGrxdHDWiweSE0T7vKBSFaoiPG13nN385tMX9NZGcGqWvnEyBBUQssCdMmEb3EFSIkwbXjxgFLyytLIvNfWwuPamwm32vi0uPxAuByCPYDuvqjY0VLh+IW7LcjAbaFhm/yhoNsJ14HcTJl1ywEvzTpfXYfLX3TwIOCEZOaXn6GLcnrrdYycI8uYIoFw0DYISHu9YcWW+zy5NSK54Yn9r96xCbNCPNQAED6NXiX3J4Jb/M7VjZLFU1M/fcA9/qwMLbosAG8AntcjZJGpWSWwmaftGUIzc1fO+qCHuMdWtQnfP+hHFbdxE50L7XzEHMSJrsS6Z7V2LYH2DR7KTP1SzWGQiRiaubqKUkQa4+1pQCHJErZAVCehKfnOSYoHJQiYFwciPvuGVUo+GgMuZgfvP7jJjeJdFOu48YIaqpsrQGVt63IWALsxxc+gzKhg0c3Fb0LCO5ZkBrxrUXqtSqDFE0OlNJWnmeEpizuaZFRKQjdO51OqAdz7Kki9/GHOx8V3wv27ZsYeBFOeYx5L/foNtgbGXf6MLr2x08JKR5OOYuVNdsh/H9BJTolF0q3MMAUJbxyBMEq+9gTA/Swi8r7h2mutTyZrjsEwd7IHh7oKWtRgQEdiW4=
